/* eslint-disable no-unused-vars */
export enum ErrorCode {
  // --- Erreurs Système & HTTP ---
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',

  // --- Authentification & Utilisateur ---
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',

  // --- Gestion des Parties ---
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  GAME_ALREADY_STARTED = 'GAME_ALREADY_STARTED',
  GAME_ALREADY_FINISHED = 'GAME_ALREADY_FINISHED',
  PLAYER_NOT_IN_GAME = 'PLAYER_NOT_IN_GAME',
  NOT_PLAYER_TURN = 'NOT_PLAYER_TURN',
  MOVE_NOT_ALLOWED = 'MOVE_NOT_ALLOWED',
  PGN_INVALID = 'PGN_INVALID',
  FEN_INVALID = 'FEN_INVALID',
  MOVE_HISTORY_NOT_FOUND = 'MOVE_HISTORY_NOT_FOUND',

  // --- Mode IA & Suggestions ---
  AI_SERVICE_ERROR = 'AI_SERVICE_ERROR',
  AI_SUGGESTION_FAILED = 'AI_SUGGESTION_FAILED',
  AI_MOVE_GENERATION_ERROR = 'AI_MOVE_GENERATION_ERROR',

  // --- Intégrations & Services Externes ---
  LLM_REQUEST_FAILED = 'LLM_REQUEST_FAILED',
  LLM_RESPONSE_INVALID = 'LLM_RESPONSE_INVALID',
}
